trigger:
  batch: true
  branches:
    include:
    - master
    - releases/*
    - features/*
  paths:
    exclude: [ 'README.md' ]

jobs:
- job: BuildLinux

  pool:
    vmImage: 'ubuntu-latest'

  variables:
    BUILD_PATH: '$(Build.BinariesDirectory)/dpp-proxy-linux'
    OUTPUT_PATH: $(BUILD_PATH)/publish/server

  steps :
    - script: |
        set -e
        git clone --depth=1 https://github.com/bitcoin-sv/dpp-proxy.git $(BUILD_PATH)
      displayName: 'clone'

    - task: GoTool@0
      inputs:
        version: '1.17.x'

    - script: |
        cd $(BUILD_PATH)
        go build -o $(OUTPUT_PATH) -ldflags="-s -w" ./cmd/server
      displayName: 'Compile'

    - task: PublishBuildArtifacts@1
      displayName: 'publish artifact'
      inputs:
        artifactName: 'LinuxDPPProxy'
        pathtoPublish: '$(BUILD_PATH)/publish'

- job: BuildMacOSX

  pool:
    vmImage: 'macOS-10.15'

  variables:
    BUILD_PATH: '$(Build.BinariesDirectory)/dpp-proxy-macosx'
    OUTPUT_PATH: $(BUILD_PATH)/publish/server

  steps :
    - script: |
        set -e
        git clone --depth=1 https://github.com/bitcoin-sv/dpp-proxy.git $(BUILD_PATH)
      displayName: 'clone'

    - task: GoTool@0
      inputs:
        version: '1.17.x'

    - script: |
        cd $(BUILD_PATH)
        go build -o $(OUTPUT_PATH) -ldflags="-s -w" ./cmd/server
      displayName: 'Compile'

    - task: PublishBuildArtifacts@1
      displayName: 'publish artifact'
      inputs:
        artifactName: 'MacOSXDPPProxy'
        pathtoPublish: '$(BUILD_PATH)/publish'

- job: BuildWindows

  pool:
    vmImage: 'windows-latest'

  variables:
    BUILD_PATH: '$(Build.BinariesDirectory)\dpp-proxy-windows'
    OUTPUT_PATH: $(BUILD_PATH)\publish\server.exe

  steps :
    - script: |
        set -e
        git clone --depth=1 https://github.com/bitcoin-sv/dpp-proxy.git $(BUILD_PATH)
      displayName: 'clone'

    - task: GoTool@0
      inputs:
        version: '1.17.x'

    - script: |
        cd $(BUILD_PATH)
        go build -o $(OUTPUT_PATH) -ldflags="-s -w" .\cmd\server
      displayName: 'Compile'

    - task: PublishBuildArtifacts@1
      displayName: 'publish artifact'
      inputs:
        artifactName: 'WindowsDPPProxy'
        pathtoPublish: '$(BUILD_PATH)\publish'
